module.exports = {
    person:{
	tableName:'person',
	fields:{
	    name:{type:'text'},
	    fbid:{type:'text'}, // unique
	    country:{type:'text'},
	    teachers:{
		type:'varchar(31)[]',
		jointype:'person'
	    },
	    schools:{
		type:'varchar(31)[]',
		jointype:'school'
	    }
	}
    },
    school:{
	tableName:'school',
	fields:{
	    name:{type:'text'},
	    country:{type:'text'},
	    teachers:{
		type:'varchar(31)[]',
		jointype:'person'
	    },
	    students:{
		type:'varchar(31)[]',
		jointype:'person'
	    }
	}
    },
    testres:{
	tableName:'testres',
	fields:{
	    student:{
		type:'varchar(31)',
		jointype:'student'
	    },
	    teacher:{
		type:'varchar(31)',
		jointype:'teacher'
	    },
	    school:{
		type:'varchar(31)',
		jointype:'school'
	    },
	    date:{type:'timestamp'},
	    grade:{type:'int'}
	}
    }
};
