module.exports = {
//fix this
    palrule : {"rule":
	       {"name":"פעל","lang":"iw","type":"v","grp":"פעל",
		"conj":{"inf":"ל12ו3",
			"past":{
			    "ms":["","",""],"ns":["","",""],"fs":["","",""],
			    "mp":["","",""],"np":["","",""],"fp":["","",""]
			},
			"present":{
			    "ms":["","","1ו23"],"ns":["","",""],"fs":["","","1ו23ת"],
			    "mp":["","","1ו23ים"],"np":["","",""],"fp":["","","1ו23ות"]
			},
			"future":{
			    "ms":["","",""],"ns":["","",""],"fs":["","",""],
			    "mp":["","",""],"np":["","",""],"fp":["","",""]
			},
			"imperative":{
			    "ms":["","",""],"ns":["","",""],"fs":["","",""],
			    "mp":["","",""],"np":["","",""],"fp":["","",""]
			}
		       },
		"hasconj":{
		    "inf":true,
		    "past":{
			"ms":[true,true,true],"ns":[true,true,true],"fs":[true,true,true],
			"mp":[true,true,true],"np":[true,true,true],"fp":[true,true,true]
		    },
		    "present":{
			"ms":[false,false,true],"ns":[false,false,false],
			"fs":[false,false,true],"mp":[false,false,true],
			"np":[false,false,false],"fp":[false,false,true]
		    },
		    "future":{
			"ms":[true,true,true],"ns":[true,true,true],"fs":[true,true,true],
			"mp":[true,true,true],"np":[true,true,true],"fp":[true,true,true]
		    },
		    "imperative":{
			"ms":[true,true,true],"ns":[true,true,true],"fs":[true,true,true],
			"mp":[true,true,true],"np":[true,true,true],"fp":[true,true,true]
		    }
		},"transform":[],"exps":[]
	       }
	      },

// fix this
    pielrule: {"rule":
	       {"name":"פיעל","lang":"iw","type":"v","grp":"פיעל",
		"conj":{"inf":"ל123",
			"past":{
			    "ms":["","",""],"ns":["","",""],"fs":["","",""],
			    "mp":["","",""],"np":["","",""],"fp":["","",""]
			},
			"present":{
			    "ms":["","","1ו23"],"ns":["","",""],"fs":["","","1ו23ת"],
			    "mp":["","","1ו23ים"],"np":["","",""],"fp":["","","1ו23ות"]
			},
			"future":{
			    "ms":["","",""],"ns":["","",""],"fs":["","",""],
			    "mp":["","",""],"np":["","",""],"fp":["","",""]
			},
			"imperative":{
			    "ms":["","",""],"ns":["","",""],"fs":["","",""],
			    "mp":["","",""],"np":["","",""],"fp":["","",""]
			}
		       },
		"hasconj":{
		    "inf":true,
		    "past":{
			"ms":[true,true,true],"ns":[true,true,true],"fs":[true,true,true],
			"mp":[true,true,true],"np":[true,true,true],"fp":[true,true,true]
		    },
		    "present":{
			"ms":[false,false,true],"ns":[false,false,false],
			"fs":[false,false,true],"mp":[false,false,true],
			"np":[false,false,false],"fp":[false,false,true]
		    },
		    "future":{
			"ms":[true,true,true],"ns":[true,true,true],"fs":[true,true,true],
			"mp":[true,true,true],"np":[true,true,true],"fp":[true,true,true]
		    },
		    "imperative":{
			"ms":[true,true,true],"ns":[true,true,true],"fs":[true,true,true],
			"mp":[true,true,true],"np":[true,true,true],"fp":[true,true,true]
		    }
		},"transform":[],"exps":[]
	       }
	      },

    testwords:[]
}
